[package]
name = "ktu-paper"
version = "0.3.0"
compiler = "0.15.0"
entrypoint = "src/lib.typ"
repository = "https://github.com/svetikas/ktu-paper"
authors = ["Dominykas Svetikas <https://svetikas.lt>"]
license = "MIT"
description = "KTU report template to use for writing lab reports or final thesis."

[template]
path = "template"
entrypoint = "main.typ"
